<?xml version="1.0" encoding="utf-8"?>
<styleLibrary office2007ColorScheme="Silver">
  <annotation>
    <lastModified>2010-06-23T00:20:26</lastModified>
  </annotation>
  <styleSets defaultStyleSet="Default">
    <styleSet name="Default" viewStyle="Office2007">
      <componentStyles>
        <componentStyle name="Inbox MonthCalendar">
          <properties>
            <property name="TitleBackColor" colorCategory="{Default}">224, 224, 224</property>
            <property name="TitleForeColor" colorCategory="{Default}">64, 64, 64</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraCalculator" useFlatMode="True" />
        <componentStyle name="UltraCombo" useFlatMode="True" />
        <componentStyle name="UltraDockManager" useFlatMode="True" />
        <componentStyle name="UltraDropDownButton" useFlatMode="True" />
        <componentStyle name="UltraExplorerBar" useFlatMode="False" />
        <componentStyle name="UltraGrid" useFlatMode="True" />
        <componentStyle name="UltraNumericEditor" buttonStyle="Button3DOldStyle">
          <properties>
            <property name="ImageTransparentColor" colorCategory="{Default}">White</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraTree" useFlatMode="True" />
      </componentStyles>
      <styles>
        <style role="Base">
          <states>
            <state name="Normal" fontName="Segoe UI" themedElementAlpha="Transparent" />
          </states>
        </style>
        <style role="DesktopAlertCaptionLink">
          <states>
            <state name="HotTracked" foreColor="Black" />
          </states>
        </style>
        <style role="DesktopAlertCloseButton">
          <states>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertDropDownButton">
          <states>
            <state name="Normal">
              <resources>
                <name>spacer</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertFooterTextLink">
          <states>
            <state name="HotTracked" foreColor="Black" fontName="Segoe UI" />
          </states>
        </style>
        <style role="DesktopAlertPinButton">
          <states>
            <state name="Normal">
              <resources>
                <name>spacer</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertTextLink">
          <states>
            <state name="HotTracked" foreColor="Black" />
          </states>
        </style>
        <style role="DotNetMonthDropDownTitle">
          <states>
            <state name="Normal" backColor="224, 224, 224" foreColor="64, 64, 64" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarControlArea">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarGroupHeader">
          <states>
            <state name="Normal" backColor="DarkOrange" foreColor="136, 85, 34" fontName="Century Gothic" borderAlpha="Opaque" fontSize="12" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarGroupItemAreaOuter">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarItem">
          <states>
            <state name="Normal" backColor="White" foreColor="5, 96, 172" fontName="Arial" borderAlpha="Opaque" fontBold="True" fontSize="11" backGradientStyle="None" backHatchStyle="None">
              <cursor>Hand</cursor>
            </state>
            <state name="HotTracked" foreColor="Teal" fontName="Arial" borderAlpha="Opaque" fontBold="True" fontSize="11">
              <cursor>Hand</cursor>
            </state>
            <state name="Active" backColor="MistyRose" foreColor="OrangeRed" fontName="Arial" borderAlpha="Opaque" fontBold="True" fontSize="11" backGradientStyle="None" backHatchStyle="None">
              <cursor>Hand</cursor>
            </state>
          </states>
        </style>
        <style role="GridAddNewBox">
          <states>
            <state name="Normal" backColor="232, 232, 232" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridAddNewBoxButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridAddNewBoxPrompt">
          <states>
            <state name="Normal" foreColor="111, 112, 116" />
          </states>
        </style>
        <style role="GridCardCaption">
          <states>
            <state name="Normal" backColor="235, 233, 237" backGradientStyle="None" backHatchStyle="None" />
            <state name="Selected" backColor="169, 177, 184" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridCell">
          <states>
            <state name="EditMode">
              <resources>
                <name>GridCellOffice2K7Black_EditMode</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridColumnHeader">
          <states>
            <state name="Normal">
              <resources>
                <name>GridColumnHeaderOffice2K7_Normal</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>GridColumnHeaderOffice2K7_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridRow">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
            <state name="Selected">
              <resources>
                <name>GridRowOffice2K7Black_Selected</name>
              </resources>
            </state>
            <state name="Active">
              <resources>
                <name>GridRowOffice2K7Black_Active</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridRowSelector">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
          </states>
        </style>
        <style role="ProgressBarFill">
          <states>
            <state name="Normal">
              <resources>
                <name>ProgressBarFill_Normal</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="ScrollBarTrackSectionRight">
          <states>
            <state name="Normal" foreColor="5, 96, 172" fontName="Century Gothic" fontSize="12" />
          </states>
        </style>
        <style role="TabCloseButton">
          <states>
            <state name="Normal" backColor="Transparent" imageBackgroundStyle="Centered" foregroundAlpha="Transparent" borderAlpha="Transparent" backGradientStyle="None" backHatchStyle="None">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAFgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAf0lEQVQ4T2P8//8/A8UAZAilmGIDwD6h1BW0MyQ1NfU/DCO7Epc4Tpfkl9X9h2GQInQ+ehDgDJPKtun/0TGu8MMbsLU9C/7DML4IwGtIff/i/zBMliFNk5b/R8ckeadl6qr/MAzSiM4nGLDtM9b9h2FkxbjEaZfYyMkGgyfvAACX0B+7d1a0bQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked" imageBackgroundStyle="Centered" foregroundAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAKQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABkklEQVQ4T5WUy0rDQBSG45PUN/IputaV4EIFEd0IiiC6FFwILhRX7owbwU2LSHHhQrCt2tqLTSbXJunx/DPJJG0VSeGjnXPO/810IFl4qDUWDcM4YJaYsp9rDqwYt/eP5vNLk5IJlQY55I2buzolbBjaAX0Ln0ZOQJYTku2FJLwxOX4O1qijjznkkJeSWEp8JRGBHFCScEai5OhjDrlcEk9owBIlgoR3c1nkKhFOgG+sUUcfczHntCTiRd/ypKharWos/DUZDKfqEGBD5AqShCU+DVLR8uoGZeDYxbUSBHLDKE5yyThKqDfyJPJELFzbOZ5jyHeGMPqYQ06fxHbH1P4S9N4T9NF36JPpDFxa3zvVdIcuAdTRxxxySmLW5KLZtanVFanMYaFDm/tnGoQA6gCbSgnnpQS3D0kmavHA1uH5HO00jD42RO5XCUTbRxcaBKbWHG6lG85IInrr2JLdk0tNVvurLryoeJJcUgz+93tK4viQWKVBLrsTs9545WckKg1yLDH5VfBUYa4YfqxLg1zlB9BexuSdtY1kAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</imageBackground>
            </state>
            <state name="Pressed" imageBackgroundStyle="Centered" foregroundAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAUQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABuklEQVQ4T52T2UrDUBRFr1+if+RX9FmfBB9UENEXQXHAAeeBatXaGm21gyltbWITkzattg5FEJWC4C9s7w70gooPMbAI55y9TibSNbu42iOEmJb0SoIecSn0C7lE15JptD8+A0OPPpfg5a2NSq0ZGHr0/SVPzy+w3Xpg6KkljYcWTKsSGHpqSbXeQNGwfUKhkKLT+6tPTy2xXQ+5gqnoGxhGB/Z/1p0sPbXEtFxk9KJPNncFPW9gcHzhF+xz3snSU0v2Do6xG4lhP6rhMJZA9OQcsdMUhiY3FKzZ55w55un5S+aW1hDXkjiMJ3xRS2ZwltKRSOcwMrWtYM0+58wxT4++WFjZxEVaxwllGTy/zCMtb3l0JvwL9jlnjnl69MXy+g6yegGJbB4pGcrKFzk2H1EUrp1vNefMMU+PvljdCiNfNJCRL02/KmNiMaowHA+GU5N43/rMMU+PvtjYjaBk2siVLBTKLko3Hkz3FuVqA5bXhCV/B55Zs885c8zToy+2wkdwKjV/wKuWq3ew6/dw7h7hNFpwmy3/zJp9zpljnh59IT+VnpHP+PreDgw9+mLvSOuWHEvwD+h1fwFZJmJEnZO7ZAAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
          </states>
        </style>
        <style role="TabControlTabCloseButton">
          <states>
            <state name="Normal" backColor="Transparent" imageBackgroundStyle="Centered" borderAlpha="Transparent" backGradientStyle="None" backHatchStyle="None">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAFgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAf0lEQVQ4T2P8//8/A8UAZAilmGIDwD6h1BW0MyQ1NfU/DCO7Epc4Tpfkl9X9h2GQInQ+ehDgDJPKtun/0TGu8MMbsLU9C/7DML4IwGtIff/i/zBMliFNk5b/R8ckeadl6qr/MAzSiM4nGLDtM9b9h2FkxbjEaZfYyMkGgyfvAACX0B+7d1a0bQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked" imageBackgroundStyle="Centered" borderAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAKQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABkklEQVQ4T5WUy0rDQBSG45PUN/IputaV4EIFEd0IiiC6FFwILhRX7owbwU2LSHHhQrCt2tqLTSbXJunx/DPJJG0VSeGjnXPO/810IFl4qDUWDcM4YJaYsp9rDqwYt/eP5vNLk5IJlQY55I2buzolbBjaAX0Ln0ZOQJYTku2FJLwxOX4O1qijjznkkJeSWEp8JRGBHFCScEai5OhjDrlcEk9owBIlgoR3c1nkKhFOgG+sUUcfczHntCTiRd/ypKharWos/DUZDKfqEGBD5AqShCU+DVLR8uoGZeDYxbUSBHLDKE5yyThKqDfyJPJELFzbOZ5jyHeGMPqYQ06fxHbH1P4S9N4T9NF36JPpDFxa3zvVdIcuAdTRxxxySmLW5KLZtanVFanMYaFDm/tnGoQA6gCbSgnnpQS3D0kmavHA1uH5HO00jD42RO5XCUTbRxcaBKbWHG6lG85IInrr2JLdk0tNVvurLryoeJJcUgz+93tK4viQWKVBLrsTs9545WckKg1yLDH5VfBUYa4YfqxLg1zlB9BexuSdtY1kAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</imageBackground>
            </state>
            <state name="Pressed" imageBackgroundStyle="Centered" borderAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAUQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABuklEQVQ4T52T2UrDUBRFr1+if+RX9FmfBB9UENEXQXHAAeeBatXaGm21gyltbWITkzattg5FEJWC4C9s7w70gooPMbAI55y9TibSNbu42iOEmJb0SoIecSn0C7lE15JptD8+A0OPPpfg5a2NSq0ZGHr0/SVPzy+w3Xpg6KkljYcWTKsSGHpqSbXeQNGwfUKhkKLT+6tPTy2xXQ+5gqnoGxhGB/Z/1p0sPbXEtFxk9KJPNncFPW9gcHzhF+xz3snSU0v2Do6xG4lhP6rhMJZA9OQcsdMUhiY3FKzZ55w55un5S+aW1hDXkjiMJ3xRS2ZwltKRSOcwMrWtYM0+58wxT4++WFjZxEVaxwllGTy/zCMtb3l0JvwL9jlnjnl69MXy+g6yegGJbB4pGcrKFzk2H1EUrp1vNefMMU+PvljdCiNfNJCRL02/KmNiMaowHA+GU5N43/rMMU+PvtjYjaBk2siVLBTKLko3Hkz3FuVqA5bXhCV/B55Zs885c8zToy+2wkdwKjV/wKuWq3ew6/dw7h7hNFpwmy3/zJp9zpljnh59IT+VnpHP+PreDgw9+mLvSOuWHEvwD+h1fwFZJmJEnZO7ZAAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
          </states>
        </style>
        <style role="TreeCell">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
          </states>
        </style>
        <style role="UltraButton" buttonStyle="FlatBorderless">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraCalculator">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraCalculatorButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>Button_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraCalculatorButtonBase">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraDropDownButtonMainButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraDropDownButtonSplitButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraNumericEditor" buttonStyle="Button3DOldStyle">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraProgressBar" borderStyle="Rounded1">
          <states>
            <state name="Normal" borderColor="169, 177, 184" />
          </states>
        </style>
        <style role="UnpinnedTabAreaTop">
          <states>
            <state name="Normal" backColor="208, 212, 221" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
      </styles>
    </styleSet>
  </styleSets>
  <resources>
    <resource name="Button" foreColor="75, 75, 75" borderColor="Transparent" fontName="Segoe UI" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAGwIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABhElEQVRIS62Vu0oDURCGRxEfzcrWd1HwUniBmIARiRcimAgqKCJKKitLEbQwxrgm62Zv2Us2MVErEX9nFrTRSmbhK8/375k5c84QADqqnIP+8b1/fvysGh0e+WWYGB8bor3TCi4ur2C126qIU9y0c3wCr9PB/ZOliun5EDcV9w8RJV0YLVsVOwghbiqU9hD3nmHYjipuHEPctLK9g6Q/wKPjqhJ0EoibMuub6A1e0HA8VcJuD+Km+dU19F/f0OQATbpcFXHTbHYFAw7Q3kHy3Ie4aXopi4SbfGs0VPGjGOKmyYVlSENuanVVWn4b4uaADKRe1YdHVUL+aXHT1OJyOmhVLpEmDg+auGkmk0PMR6rWMFXxggjiprlcPg2oN59UccMI4qYFPqtSorppqeJyicRN2cIWIt6BYfFlp4jDOxA35YulNKBpu6q43ANx00Z5Pw0wXV8VhwPETdsHR+l13fIDVdwwhripzK/OdfUuHTZNxClukkf/4KyC/7B7fIpv/lov7i+3fvRP8rl7GwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="Button_HotTracked" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAMQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABmklEQVRIS63VSyuEYRjG8Vs2PodPgwU2iCisRLFQbMhhFhKihsIC5ZChhpwih5LJYpCZNIlEDpPJISFhmLlc9zvYsOJ+6794F8/veQ/dPUkApGP6GPKH6+Ul9r0qJSX5h1CdnZokLRMH8PpOgbeIaWqqLa6xPcSj4UTPIbvoqS31Q7uIv54h/hSwjabaUtvv51OfIPbgN01NtaXS7UPs6RDvdxumqam2lLWvIvYYwtvNCls2asUx1ZbSlkW83wcQjcyyGaNmHVNtKXTN89P4EQ172LhRHsdUW/IbpoGzTiCQztKMokVTbcmpn+JNF+GMz010o/9Gi6baklPnBc7dQDCLZRpFi6bakqtvcNEL7OWxXKNo0VRbCvQfhAeAUAkrNooWTbWlyDUHXI4A+xWs3ChaNNXmHCwAkUngsJbVGEWLptrOJONqBjhqZk1G0aLpTHKVex24XgRO2lmbUbRoqi01fZvA7Rpw2sO6jaJFU22eB1vAnS9ReNAuemqLazSIpR0el6/bpqmptuih3+oJ4S81Dgfx1W/r1f4AnTS4cppalG4AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
    </resource>
    <resource name="DesktopAlertDropDownButton_HotTracked" backColor="255, 231, 162" foreColor="Black" borderColor="255, 189, 105" backGradientStyle="None" backHatchStyle="None" />
    <resource name="GridCellOffice2K7Black_EditMode" backColor="Transparent" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAATQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAGQAAAB8IBgAAABKwZn4AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAtklEQVRIS+2WsQoDIRBEPTvxo0J+/I58iaidrYiVbhwJR8osaKpdsJFlxn1uMYdzTllrr1rro/d+qEWltSZjzKuU8lQppSuEQMOEhgmtKuhBF/rKe99xsaNyzgR9NXBRa22Hx9SF/jTZWWLCoiu4BBeLAKtZtktwsQiwmmW7BBeLAKv5v9u1Mjl+j3nnLiS8kVdZCH5tvhPkyKpnjJFwsWoiTICHf7LwiQQ5QzcmwietOtCDLvTfKKCXZicmfD4AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridColumnHeaderOffice2K7_HotTracked" backColor="Transparent" borderColor="242, 149, 54" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAGwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAPwAAABMIBgAAACcx1ZIAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAhElEQVRYR+XDwQoBUQCF4eNJLZSFslAWykJZKAtloSxm4VkQQkYIzWPM3Jk7Y3U8yP/V1/plG4uq+SamVvNZm1r1e2Vq1a+lqRWfC1MrPuamVrzPTK0qnZpa1W1iapXXsalVXkamVjgPTa1wGpha4dg3tYpDz9Qq9l1TK991TK182zb1H6/IWkPV8UmbAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridColumnHeaderOffice2K7_Normal" backColor="246, 250, 251" foreColor="75, 75, 75" borderColor="195, 195, 195" imageBackgroundStyle="Stretched" fontBold="True" backColor2="210, 210, 210" backGradientStyle="Vertical" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridRowOffice2K7Black_Active" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAATQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAGQAAAB8IBgAAABKwZn4AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAtklEQVRIS7XDQWfCAQDG4XefLGJ0iNghxg4xdohmFNkOO+3SZaddOnXpVESMKOVPZFO22SxLjH2R97dP8T48JxxGKI39kHTxNSBdfPRJF29PpIvtI+nipUe62DyQLtb3pIvilnSxapMuFteki3GJdHlSJl2enpIuP1dIl2dV0uV5jXR5eUa6XNRJl9fnpMubC9Ll1wbp8u6SdPn9inT5s0m6/N0iXf65IV0+dkiXf7uky393pP8Do3pdmMPchykAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridRowOffice2K7Black_Selected" foreColor="Black" imageBackgroundStyle="Stretched">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAACwEAAAKJUE5HDQoaCgAAAA1JSERSAAAACwAAABQIBgAAAFssx2gAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAdElEQVQ4T5XQOwrCYAAE4fX+9xHBwsLGxkKwESwshIAm8UUiPv6MOcK48HVT7YTSEzu+LVb41FgZ3iesDK8KK+V5xErpD+MhTkq3xwr1FOvPuJmBFJr5GDuhXWCFyxIrXFdY4bbGCvcNVnhssUK3wwrljPUDYL0XRV2kXHAAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ProgressBarFill_Normal" backColor="Transparent" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="0, 1, 0, 1">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAJgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABcIBgAAAAL2z9kAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAj0lEQVQ4T6XUXwoBUQCF8WMLc28ezNiSpUiRkMifNA+WpaSklOYOKVnJca3hO/V7/R5Pp7sbWGR1ezShfapNaNMcTGjVbE1o0axNaJaWJjRJcxMatVMTGj7HJlSceiZUnHMAUHEpTShcSxMKtxwAFO45ACg8KhMKKQcAxVdlQvHdN6H4yQFA8ZsDgP6vTPwAQjc1pbxSJB4AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="spacer" backColor="Transparent" borderColor="Transparent" backGradientStyle="None" backHatchStyle="None">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAqQAAAAKJUE5HDQoaCgAAAA1JSERSAAAAAgAAAAIIBgAAAHK2DSQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAEklEQVQYV2P8//8/AxiAGCAMAE3WCPnXj6AWAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="TabControlTabItemHorizontalBottomOffice2k7Black_Selected" foreColor="Black" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="6, 0, 5, 3">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAAQQAAAKJUE5HDQoaCgAAAA1JSERSAAAANgAAABYIBgAAAIvpb+sAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAADaklEQVRYR9XW2U7bUBAGYEdVy1Vp+2y8ADcIHoYbBA/AC3CFVDaVJpSCKrXQliWQ3dmceHc2J2zTf+IkXuJQUeciRfrkjXMyY88cO7aXytK7D++FecMU7O6DEBPC/+bmXk+48pLTk2Z/yRxCaIyxWEx4M/dKaL2dFyRZFoTPJ6d00OhRtlChH79v6WyCq9scRZfHHNFdY46gZKpA5apMJ+07Ojg6JiEej9Nu54HyRYnOL1Khfl6miAfOjDRi8bhJi8SqNZUS9gMdHh66iYlliX5dpSe6yWBwRLcYP3XZIt1CCqQ6J/boJJZIJGgfWZYqdbpIZvsub3Jj0rkSRZYvU3oKMpjDi9uI1RWdvnQ9ie0hS65Pp4fcHrhOoZYHsoUyBs8IEYkM5LB1VElWA4ntI7GKpLg9hPq9CchjYGRFzDFlBcxXwPpQKEmkaAZ99T6xAxxUa0pI/aN+Mw4eOCvEUo1GyjUqDqi6SSc9TylyYjU0XjpXHMmgp7yGg6NsS5Uaenka6v01gZWrLt2w6HSYGC/3H+0nqsvaqCGzaM6gEiaIyhtEtH25vyawCpMcutFAYk/ucr/DiWFFyWFx6BPHlTEwqmEA09xWERe3ETPMkMQU1UATciNWSWQlPwkDZwbaht9ZQ9xGzLSawSf2SKpmogmlkRIa0qsmY/CM4LbxUXAMVqNFp3eeUvyE7yteUSroI9egfgd1LKNUZ4WC99U4gxrNQGLHzS5pSOy5UlPxjphVGmLj+Juttv+Jfbfa/Qt1lNokfH1W6IaJFTDIolY7kFjSaJKOwBVVm0jFNRUl4KPheAIN5310vqsGfscrLEDnnOFjYcVzmdgfY1nUbnfcJ8YfwUW82HgyTUcwI04gXv6ggkHi2PDyB22YCNYnJDgOGAEGWVaDfBo4DtHpdOjb8AW9u7tLNdSobXdfpov/H9PDOUc3qIdzHj3sT9cdtTo2ndn3tL29TcL6+jqJoojH2P5HnX4J/A3fTYcdyrZt3NgIcCNVPJxzrBNra2skLC8vE39W5fN59A9eciiX55LkBh1qYt+rgWNHhxpIwhowsTXwo0wfwtPWEYzmoXJwQ3iiah9eRWPucc6lYL+MeZOyQvGjI1paWiJhYWGBFhcXaXV1lTY3N2lra6v/rfW/2dnZoY2NDVpZWSHO6Q+FLEZgxYICBwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
  </resources>
</styleLibrary>