//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWA4.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDBPathName {
            get {
                return ((string)(this["LastDBPathName"]));
            }
            set {
                this["LastDBPathName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09")]
        public string ApplicationVersionKey {
            get {
                return ((string)(this["ApplicationVersionKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int tMaxNumberofSites {
            get {
                return ((int)(this["tMaxNumberofSites"]));
            }
            set {
                this["tMaxNumberofSites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int tMaxNumberofFoodTypes {
            get {
                return ((int)(this["tMaxNumberofFoodTypes"]));
            }
            set {
                this["tMaxNumberofFoodTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int tMaxNumberofLossTypes {
            get {
                return ((int)(this["tMaxNumberofLossTypes"]));
            }
            set {
                this["tMaxNumberofLossTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int tMaxNumberofUserTypes {
            get {
                return ((int)(this["tMaxNumberofUserTypes"]));
            }
            set {
                this["tMaxNumberofUserTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int tMaxNumberofDETs {
            get {
                return ((int)(this["tMaxNumberofDETs"]));
            }
            set {
                this["tMaxNumberofDETs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int tMaxNumberofReports {
            get {
                return ((int)(this["tMaxNumberofReports"]));
            }
            set {
                this["tMaxNumberofReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int tMaxNumberofTrackers {
            get {
                return ((int)(this["tMaxNumberofTrackers"]));
            }
            set {
                this["tMaxNumberofTrackers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tAddUsersAvailable {
            get {
                return ((bool)(this["tAddUsersAvailable"]));
            }
            set {
                this["tAddUsersAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tAMWTAvailable {
            get {
                return ((bool)(this["tAMWTAvailable"]));
            }
            set {
                this["tAMWTAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tConfiguratorAvailable {
            get {
                return ((bool)(this["tConfiguratorAvailable"]));
            }
            set {
                this["tConfiguratorAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tEnterFinancialsAvailable {
            get {
                return ((bool)(this["tEnterFinancialsAvailable"]));
            }
            set {
                this["tEnterFinancialsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tEnterSWATNotesAvailable {
            get {
                return ((bool)(this["tEnterSWATNotesAvailable"]));
            }
            set {
                this["tEnterSWATNotesAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tFoodCostAdjustmentsAvailable {
            get {
                return ((bool)(this["tFoodCostAdjustmentsAvailable"]));
            }
            set {
                this["tFoodCostAdjustmentsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tImportWasteDataAvailable {
            get {
                return ((bool)(this["tImportWasteDataAvailable"]));
            }
            set {
                this["tImportWasteDataAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageBaselinesAvailable {
            get {
                return ((bool)(this["tManageBaselinesAvailable"]));
            }
            set {
                this["tManageBaselinesAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageDETsAvailable {
            get {
                return ((bool)(this["tManageDETsAvailable"]));
            }
            set {
                this["tManageDETsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageEventClientsAvailable {
            get {
                return ((bool)(this["tManageEventClientsAvailable"]));
            }
            set {
                this["tManageEventClientsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageEventOrdersAvailable {
            get {
                return ((bool)(this["tManageEventOrdersAvailable"]));
            }
            set {
                this["tManageEventOrdersAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManagePreferencesAvailable {
            get {
                return ((bool)(this["tManagePreferencesAvailable"]));
            }
            set {
                this["tManagePreferencesAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManagePrintFormsAvailable {
            get {
                return ((bool)(this["tManagePrintFormsAvailable"]));
            }
            set {
                this["tManagePrintFormsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageReportsSettingsAvailable {
            get {
                return ((bool)(this["tManageReportsSettingsAvailable"]));
            }
            set {
                this["tManageReportsSettingsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageSitesAvailable {
            get {
                return ((bool)(this["tManageSitesAvailable"]));
            }
            set {
                this["tManageSitesAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageTrackersAvailable {
            get {
                return ((bool)(this["tManageTrackersAvailable"]));
            }
            set {
                this["tManageTrackersAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tManageTypesAvailable {
            get {
                return ((bool)(this["tManageTypesAvailable"]));
            }
            set {
                this["tManageTypesAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tRecurringTransactionsAvailable {
            get {
                return ((bool)(this["tRecurringTransactionsAvailable"]));
            }
            set {
                this["tRecurringTransactionsAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tRemoveUsersAvailable {
            get {
                return ((bool)(this["tRemoveUsersAvailable"]));
            }
            set {
                this["tRemoveUsersAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tUpdateTrackerAvailable {
            get {
                return ((bool)(this["tUpdateTrackerAvailable"]));
            }
            set {
                this["tUpdateTrackerAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tConfigureDaypartEntryAvailable {
            get {
                return ((bool)(this["tConfigureDaypartEntryAvailable"]));
            }
            set {
                this["tConfigureDaypartEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tConfigureDispositionEntryAvailable {
            get {
                return ((bool)(this["tConfigureDispositionEntryAvailable"]));
            }
            set {
                this["tConfigureDispositionEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tConfigurePrePostEntryAvailable {
            get {
                return ((bool)(this["tConfigurePrePostEntryAvailable"]));
            }
            set {
                this["tConfigurePrePostEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tConfigureStationEntryAvailable {
            get {
                return ((bool)(this["tConfigureStationEntryAvailable"]));
            }
            set {
                this["tConfigureStationEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tDaypartEntryAvailable {
            get {
                return ((bool)(this["tDaypartEntryAvailable"]));
            }
            set {
                this["tDaypartEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tDispositionEntryAvailable {
            get {
                return ((bool)(this["tDispositionEntryAvailable"]));
            }
            set {
                this["tDispositionEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tPrePostEntryAvailable {
            get {
                return ((bool)(this["tPrePostEntryAvailable"]));
            }
            set {
                this["tPrePostEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tStationEntryAvailable {
            get {
                return ((bool)(this["tStationEntryAvailable"]));
            }
            set {
                this["tStationEntryAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tAdvancedMenuAvailable {
            get {
                return ((bool)(this["tAdvancedMenuAvailable"]));
            }
            set {
                this["tAdvancedMenuAvailable"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://activate.leanpath.com/UpdateManager.asmx")]
        public string VWA4_com_leanpath_activate_UpdateManager {
            get {
                return ((string)(this["VWA4_com_leanpath_activate_UpdateManager"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationId {
            get {
                return ((string)(this["ApplicationId"]));
            }
            set {
                this["ApplicationId"] = value;
            }
        }
    }
}
